project_id           = "home-258016"
region               = "us-central1"
zone                 = "us-central1-a"
gce_ssh_user         = "demo"
ssh_private_key_file = "id_ed25519"
ssh_public_key_file  = "id_ed25519.pub"
